### PR TITLE
improve handling for partial HTML from HEEx lexer

### PR DESCRIPTION
**Pull request by SteffenDE**
The HEEx lexer creates HTML that contains empty attributes like `<div id=></div>` when lexing `<div id={@foo}></div>`. This leads to the HTML lexer lexing following closing tags as attributes.

Before:
image

After:
image

### CODE REVIEW

**Comment by SteffenDE** [comment]
This can also be seen in the HEEx demo: https://elixir-makeup.github.io/makeup_demo/heex.html#default

image

Notice the closing `</div>` being rendered in the attribute color.

**Review by javiergarea — APPROVED** [review]
LGTM 🚀

**Comment by javiergarea** [comment]
Would you mind taking a quick look at this? A second set of eyes would be great 😄 @josevalim

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Pull request merged**
